In [5]:
import numpy as np


In [6]:
arr=np.array([[1,3,2],
            [2,3,3]])


print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr.ndim

2

## Markdown

# Heading


In [8]:
arr.shape

(2, 3)

In [11]:
a=np.array([[1,2,4],
          [2,4,6],
          [2,7,7]],dtype='float')
a

array([[1., 2., 4.],
       [2., 4., 6.],
       [2., 7., 7.]])

In [19]:
c=np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
b=np.zeros((1,2))
b

array([[0., 0.]])

In [22]:
np.arange?

In [23]:
f=np.arange(0,30,5)
f

array([ 0,  5, 10, 15, 20, 25])

In [25]:
f2=np.linspace(0,30,5)
f2

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [32]:
arr=np.array([[1,2,3,4],
             [3,4,45,4],
             [3,3,3,3]])
newarr=arr.reshape((2,6))
print(newarr,'\n','\n')
print(arr)

[[ 1  2  3  4  3  4]
 [45  4  3  3  3  3]] 
 

[[ 1  2  3  4]
 [ 3  4 45  4]
 [ 3  3  3  3]]


In [34]:
arr.flatten()

array([ 1,  2,  3,  4,  3,  4, 45,  4,  3,  3,  3,  3])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr.max()

45

In [37]:
arr.max(axis=1)

array([ 4, 45,  3])

In [38]:
arr.max(axis=0)

array([ 3,  4, 45,  4])

In [39]:
arr.min()

1

In [47]:
print(arr[1:][1:3])

[[3 3 3 3]]


In [50]:
b=arr+1
b

array([[ 2,  3,  4,  5],
       [ 4,  5, 46,  5],
       [ 4,  4,  4,  4]])

In [51]:
b*4

array([[  8,  12,  16,  20],
       [ 16,  20, 184,  20],
       [ 16,  16,  16,  16]])

In [52]:
b.sum()

90

In [53]:
b.sum(axis=0)

array([10, 12, 54, 14])

In [58]:
np.vstack?